# Generated by Django 4.0.4 on 2022-07-23 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_system', models.CharField(blank=True, choices=[('Art', 'Art'), ('Chemistry', 'Chemistry'), ('Technical Devices', 'Technical Devices'), ('Cooking', 'Cooking'), ('Music', 'Music')], max_length=30)),
                ('title', models.CharField(max_length=250)),
                ('Beschreibung', models.CharField(max_length=250)),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('not_av_slots', models.JSONField(null=True)),
                ('av_slots', models.JSONField(null=True)),
                ('clusterr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.cluster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users_reservations_dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_av_slots', models.JSONField(null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrikelnummer', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.AddConstraint(
            model_name='users_reservations_dict',
            constraint=models.UniqueConstraint(fields=('reservation', 'user'), name='unique_user_reservation'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('clusterr', 'date'), name='unique_reservation'),
        ),
    ]
