# Generated by Django 4.0.4 on 2022-06-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Nutzer',
        ),
        migrations.DeleteModel(
            name='freeDates',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cluster',
            name='Beschreibung',
            field=models.CharField(default=-1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='tag_system',
            field=models.CharField(blank=True, choices=[('Art', 'Art'), ('Chemistry', 'Chemistry'), ('Technical Devices', 'Technical Devices'), ('Cooking', 'Cooking'), ('Music', 'Music')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='availability',
            field=models.BooleanField(),
        ),
    ]
