# Generated by Django 4.0.4 on 2022-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_rename_user_nutzer_delete_freedates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.IntegerField(choices=[(0, '08:00 – 10:00'), (1, '10:00 – 12:00'), (2, '12:00 – 14:00'), (3, '14:00 – 16:00'), (4, '16:00 – 18:00'), (5, '18:00 – 20:00')])),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
